import re
import random

# EcoBot local responder database
RESPONSES = {
    "greeting": [
        "Hello! I am EcoBot, your environmental assistant. How can I help you protect the planet today?",
        "Hi there! Ready to learn about sustainability and complete some quests? Ask me anything!",
        "Welcome! I can help you with recycling tips, carbon footprint facts, renewable energy, and more. What's on your mind?"
    ],
    "climate": [
        "**Climate Change** is caused by the increase of greenhouse gases (like CO2 and methane) trapping heat in Earth's atmosphere.\n\n**Key Actions you can take:**\n1. Use energy-efficient LED bulbs.\n2. Walk or bike instead of driving short distances.\n3. Support renewable energy sources.\n4. Plant trees to capture carbon dioxide.",
        "The Earth's average temperature has risen by about 1.1°C since the pre-industrial era, primarily driven by burning fossil fuels. Every fraction of a degree matters! Reducing your footprint helps mitigate extreme weather and sea-level rise."
    ],
    "recycle": [
        "Recycling is crucial! Here's a quick guide:\n- **Organic (Green Bin):** Food waste, fruit peels, eggshells, garden waste. They biodegrade and make compost!\n- **Recyclable (Blue Bin):** Clean paper, cardboard, plastic bottles, glass jars, metal cans. Make sure they are washed and dry!\n- **Hazardous (Red/Orange Bin):** Batteries, electronic waste, lightbulbs, paint, chemicals. These need special disposal centers so they don't leak toxins into the soil.",
        "Before recycling, try to **Reduce** and **Reuse** first! Reducing packaging waste is much more effective than recycling it later. When you do recycle, avoid 'wishcycling' (throwing non-recyclables in the blue bin), as it contaminates the batch."
    ],
    "energy": [
        "Renewable energy comes from natural, infinite sources:\n- **Solar Power:** Captures light from the sun using PV panels.\n- **Wind Energy:** Uses massive turbines to generate electricity from air currents.\n- **Hydroelectric:** Uses flowing water to turn generator turbines.\n\nBy transitioning from coal and gas to renewables, we can eliminate over 70% of global electricity emissions!"
    ],
    "water": [
        "Water is a precious resource. Only 1% of the Earth's water is fresh and accessible! You can save water by:\n- Taking shorter showers (5 minutes or less).\n- Turning off the tap while brushing teeth or washing dishes.\n- Fixing leaks promptly.\n- Collecting rainwater for watering plants."
    ],
    "plastic": [
        "Over **380 million tons** of plastic are produced every year, and half of it is single-use! It takes plastic up to 500 years to break down, and it often breaks into microplastics that contaminate our oceans, food, and bodies.\n\n**Tips to reduce plastic:**\n1. Carry a reusable water bottle and shopping bag.\n2. Avoid plastic straws and utensils.\n3. Buy groceries in bulk to reduce packaging."
    ],
    "biodiversity": [
        "Biodiversity is the variety of life on Earth. Ecosystems depend on every single species to remain stable. Forests, wetlands, and coral reefs are crucial for clean air, water, and climate regulation.\n\n**How to protect biodiversity:**\n- Avoid using synthetic pesticides in gardens.\n- Support local conservation efforts.\n- Plant native wildflowers to attract bees and pollinators!"
    ],
    "carbon": [
        "A **Carbon Footprint** is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.\n\nUse our **Carbon Footprint Calculator** to check your score! The average global carbon footprint is about 4 tons per person, but to avoid 2°C warming, we need to bring it down to under 2 tons."
    ],
    "garden": [
        "In your **Virtual Eco Garden**, you can plant and grow various trees and flowers by spending **Eco Coins** earned through lessons and quizzes.\n\nTo make your garden thrive:\n- Complete Daily Challenges.\n- Ace your Quizzes.\n- Log in daily to check on growth stages!"
    ],
    "city": [
        "The **Green City Simulator** allows you to build a sustainable municipality. Install solar panels and parks to reduce pollution and make citizens happy! Be careful: constructing too much without balancing green cover will drop your Air Quality Index."
    ],
    "default": [
        "That's an interesting question! While I might not have a specific response for that, remember that small daily choices—like switching off lights, reducing plastic, and reusing items—add up to make a huge impact on our environment.",
        "I'm still learning! You can ask me about: **Climate Change**, **Recycling**, **Renewable Energy**, **Water Saving**, **Reducing Plastic**, **Biodiversity**, or how to use the **Eco Garden** and **City Simulator**.",
        "Fascinating query! A great way to learn more is by heading to the **Learning Zone** to read modules on Climate, Water, and Sustainable Living."
    ]
}

def get_bot_response(user_message):
    message = user_message.lower().strip()
    
    # Check key categories
    if re.search(r'\b(hi|hello|hey|greetings|bot|ecobot)\b', message):
        return random.choice(RESPONSES["greeting"])
    elif re.search(r'\b(climate|global warming|greenhouse|co2|atmosphere|temperature|carbon dioxide)\b', message):
        return random.choice(RESPONSES["climate"])
    elif re.search(r'\b(recycle|trash|bin|garbage|waste|compost|organic|segregat)\b', message):
        return random.choice(RESPONSES["recycle"])
    elif re.search(r'\b(energy|solar|wind|power|electric|hydro|renewable|fossil|coal)\b', message):
        return random.choice(RESPONSES["energy"])
    elif re.search(r'\b(water|shower|tap|leak|rain|river|ocean|pollution)\b', message):
        return random.choice(RESPONSES["water"])
    elif re.search(r'\b(plastic|bag|bottle|microplastic|single-use|straw)\b', message):
        return random.choice(RESPONSES["plastic"])
    elif re.search(r'\b(biodiversity|forest|deforest|wildlife|animal|tree|bee|species|extinct)\b', message):
        return random.choice(RESPONSES["biodiversity"])
    elif re.search(r'\b(carbon|footprint|calculator|co2|emission)\b', message):
        return random.choice(RESPONSES["carbon"])
    elif re.search(r'\b(garden|plant|seed|flower|tree|grow|eco coin)\b', message):
        return random.choice(RESPONSES["garden"])
    elif re.search(r'\b(city|simulator|build|solar panel|park|happiness|pollution index)\b', message):
        return random.choice(RESPONSES["city"])
    
    return random.choice(RESPONSES["default"])
